name: CI

on:
  push:
  pull_request:

jobs:
  build-lint-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: ESLint
        run: npm run lint

      - name: Prettier Format Check
        run: npm run format:check

      - name: Prettier Format
        run: npm run format
